### ISSUE TITLE
Fix reservation list page and payment page design

### ISSUE THREAD

**Issue by tsudmi** [crypotex/taas#119]
**/reservation/list** - change position of buttons, add design to total price.
**/reservation/payment/budget/** - add design to the password form, pay button and validation errors.
**/** - add image of the fields, colors legend,  fix position of the submit button
**/reservation/history/** - make size of the page bigger, so that number of reservations at the end of the page will have more space after them. Put "submit" button more in the center of the page.
![screenshot from 2015-11-26 16 16 46](https://cloud.githubusercontent.com/assets/6001614/11424837/2a6d6b82-9459-11e5-895c-0708a6587781.png)

**/user/balance/** - remove number 1 from the form.

**Comment by viktoriap** [comment]
Blocked by issue #31
