### ISSUE TITLE
Frontend: Add and test browser support

### ISSUE THREAD

**Issue by crypotex** [crypotex/taas#70]
firefox, chrome etc
NFRs: 
TAAS should run on multiple latest browsers (IE9+, Firefox 26+, Chrome 30+).
TAAS should run on mobile device default browsers.

**Comment by dummyanni** [comment]
Tested browser support for both mobile and desktop. 
http://try.powermapper.com/Reports/329e2c28-6f01-43a5-b144-b6971bd1665c/report/map.BUG.htm
