### ISSUE TITLE
Testing: Calender testing and reservation testing

### ISSUE THREAD

**Issue by crypotex** [crypotex/taas#75]
Name says all.

**Comment by tsudmi** [comment]
Consider writing tests on following topics:
- Adding reservations to the calendar (test ajax views and database objects)
- Removing reservations from the calendar (test ajax views and database objects)
- Added unpaid reservations are removed after timer has bee expired.
- Added unpaid reservations appear on the reservation list page.
- Test permissions (who is allowed what to do.)
